/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps, useNavigateAction } from "./utils";
import { Image, Text, View } from "@aws-amplify/ui-react";
export default function Animal(props) {
  const { animal, overrides, ...rest } = props;
  const xOnClick = useNavigateAction({ type: "url", url: "/" });
  return (
    <View
      width="349px"
      height="666px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Animal")}
      {...rest}
    >
      <View
        width="349px"
        height="510.77px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="23.31%"
        left="0%"
        right="0%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor={animal?.cor}
        {...getOverrideProps(overrides, "Rectangle 1164")}
      ></View>
      <View
        width="349px"
        height="404.84px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="39.21%"
        bottom="0%"
        left="0%"
        right="0%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(236,236,236,1)"
        {...getOverrideProps(overrides, "Rectangle 1166")}
      ></View>
      <View
        width="77px"
        height="24.12px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.46%"
        bottom="83.92%"
        left="4.58%"
        right="73.35%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor={
          animal?.alimentacao == "Herbivoro" ? "#41B507" : "#CD2D0A"
        }
        {...getOverrideProps(overrides, "Rectangle 1165")}
      ></View>
      <Image
        width="49.86%"
        height="26.73%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.31%"
        bottom="60.96%"
        left="26.36%"
        right="23.78%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        src={animal?.imagem}
        {...getOverrideProps(overrides, "pregui\u00E7a 1")}
      ></Image>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="316px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="9.13%"
        bottom="87.24%"
        left="4.58%"
        right="4.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.especie}
        {...getOverrideProps(overrides, "Bicho-Pregui\u00E7a")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="48px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="43.94%"
        bottom="52.44%"
        left="6.88%"
        right="79.37%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sobre"
        {...getOverrideProps(overrides, "Sobre")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50.71%"
        bottom="45.67%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Especie"
        {...getOverrideProps(overrides, "Especie")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.01%"
        bottom="40.37%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Idade"
        {...getOverrideProps(overrides, "Idade")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="72.22%"
        bottom="24.16%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Habitat"
        {...getOverrideProps(overrides, "Habitat")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="77.63%"
        bottom="18.75%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Especialista"
        {...getOverrideProps(overrides, "Especialista")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="93.84%"
        bottom="2.53%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Comentários"
        {...getOverrideProps(overrides, "Coment\u00E1rios")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="61.41%"
        bottom="34.97%"
        left="6.88%"
        right="51%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Temperatura Ideal"
        {...getOverrideProps(overrides, "Temperatura Ideal")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="66.82%"
        bottom="29.56%"
        left="6.88%"
        right="51%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="BPM Ideal"
        {...getOverrideProps(overrides, "BPM Ideal")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50.71%"
        bottom="45.67%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.especie}
        {...getOverrideProps(overrides, "loriem38872173")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.01%"
        bottom="40.37%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.idade}
        {...getOverrideProps(overrides, "loriem38872174")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="72.22%"
        bottom="24.16%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.habitat}
        {...getOverrideProps(overrides, "loriem38872175")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="77.63%"
        bottom="18.75%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.especialista}
        {...getOverrideProps(overrides, "loriem38872176")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.03%"
        bottom="13.34%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Peso"
        {...getOverrideProps(overrides, "Peso")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.03%"
        bottom="13.34%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.peso}
        {...getOverrideProps(overrides, "loriem38872178")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="88.44%"
        bottom="7.94%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Tamanho"
        {...getOverrideProps(overrides, "Tamanho")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="88.44%"
        bottom="7.94%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.tamanho}
        {...getOverrideProps(overrides, "loriem38872180")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="93.84%"
        bottom="2.53%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.comentarios}
        {...getOverrideProps(overrides, "loriem38872181")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="61.41%"
        bottom="34.97%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.temperaturaIdeal}
        {...getOverrideProps(overrides, "loriem38872182")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(103,103,103,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="24.12px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="66.82%"
        bottom="29.56%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.bpmIdeal}
        {...getOverrideProps(overrides, "loriem38872183")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="64px"
        height="15px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="13.06%"
        bottom="84.68%"
        left="6.59%"
        right="75.07%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.alimentacao}
        {...getOverrideProps(overrides, "Herbivoro")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="14.522727012634277px"
        textAlign="right"
        display="block"
        direction="column"
        justifyContent="unset"
        width="70px"
        height="15.73px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="10.08%"
        bottom="87.56%"
        left="75.93%"
        right="4.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.registro}
        {...getOverrideProps(overrides, "#001")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="24px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="29.045454025268555px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="316px"
        height="32.51px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="4.25%"
        bottom="90.87%"
        left="4.58%"
        right="4.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.nome}
        {...getOverrideProps(overrides, "Manaus")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="32px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="48px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="30px"
        height="43px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="2.7%"
        bottom="90.84%"
        left="87.39%"
        right="4.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="X"
        onClick={() => {
          xOnClick();
        }}
        {...getOverrideProps(overrides, "X")}
      ></Text>
    </View>
  );
}
