/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Image, Text, View } from "@aws-amplify/ui-react";
export default function Floresta(props) {
  const { animal, especialista, overrides, ...rest } = props;
  return (
    <View
      width="349px"
      height="635px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Floresta")}
      {...rest}
    >
      <View
        width="349px"
        height="487px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="23.31%"
        left="0%"
        right="0%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor={animal?.cor}
        {...getOverrideProps(overrides, "Rectangle 1164")}
      ></View>
      <View
        width="349px"
        height="386px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="39.21%"
        bottom="0%"
        left="0%"
        right="0%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(236,236,236,1)"
        {...getOverrideProps(overrides, "Rectangle 1166")}
      ></View>
      <View
        width="77px"
        height="23px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.28%"
        bottom="84.09%"
        left="2.29%"
        right="75.64%"
        borderRadius="50px"
        padding="0px 0px 0px 0px"
        backgroundColor={animal?.grupo == "Herbivoro" ? "#41B507" : "#CD2D0A"}
        {...getOverrideProps(overrides, "Rectangle 1165")}
      ></View>
      <Image
        width="46.99%"
        height="26.46%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.76%"
        bottom="60.79%"
        left="26.65%"
        right="26.36%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        src={animal?.imagem}
        {...getOverrideProps(overrides, "pregui\u00E7a 1")}
      ></Image>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="316px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="9.13%"
        bottom="87.24%"
        left="4.58%"
        right="4.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.especie}
        {...getOverrideProps(overrides, "Bicho-Pregui\u00E7a")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="48px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="43.94%"
        bottom="52.44%"
        left="6.88%"
        right="79.37%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sobre"
        {...getOverrideProps(overrides, "Sobre")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50.71%"
        bottom="45.67%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Especie"
        {...getOverrideProps(overrides, "Especie")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.22%"
        bottom="40.16%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Idade"
        {...getOverrideProps(overrides, "Idade")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="68px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="72.76%"
        bottom="23.62%"
        left="6.88%"
        right="73.64%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Habitat"
        {...getOverrideProps(overrides, "Habitat")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="78.27%"
        bottom="18.11%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Especialista"
        {...getOverrideProps(overrides, "Especialista")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="105px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.78%"
        bottom="12.6%"
        left="6.88%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Comentários"
        {...getOverrideProps(overrides, "Coment\u00E1rios")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="61.73%"
        bottom="34.65%"
        left="6.88%"
        right="51%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Temperatura Ideal"
        {...getOverrideProps(overrides, "Temperatura Ideal")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(40,194,176,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="67.24%"
        bottom="29.13%"
        left="6.88%"
        right="51%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="BPM Ideal"
        {...getOverrideProps(overrides, "BPM Ideal")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50.71%"
        bottom="45.67%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.especie}
        {...getOverrideProps(overrides, "loriem38463965")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.06%"
        bottom="40.31%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.idade}
        {...getOverrideProps(overrides, "loriem38463966")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="72.13%"
        bottom="24.25%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.habitat}
        {...getOverrideProps(overrides, "loriem38463967")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="77.95%"
        bottom="18.43%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={especialista?.nome}
        {...getOverrideProps(overrides, "loriem38463972")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="79px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.78%"
        bottom="3.78%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.comentarios}
        {...getOverrideProps(
          overrides,
          "loriem epsilum bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla"
        )}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="61.42%"
        bottom="34.96%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.temperaturaIdeal}
        {...getOverrideProps(overrides, "loriem38463969")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="15px"
        fontWeight="700"
        color="rgba(66,66,66,1)"
        lineHeight="18.15340805053711px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="66.77%"
        bottom="29.61%"
        left="51.29%"
        right="6.59%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.bpmIdeal}
        {...getOverrideProps(overrides, "loriem38463970")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="14.522727012634277px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="113px"
        height="23px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="12.76%"
        bottom="83.62%"
        left="4.58%"
        right="63.04%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.grupo}
        {...getOverrideProps(overrides, "Herbivoro")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="14.522727012634277px"
        textAlign="right"
        display="block"
        direction="column"
        justifyContent="unset"
        width="70px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="12.76%"
        bottom="82.83%"
        left="77.65%"
        right="2.29%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.registro}
        {...getOverrideProps(overrides, "#001")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="24px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="29.045454025268555px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="316px"
        height="31px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="4.25%"
        bottom="90.87%"
        left="4.58%"
        right="4.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={animal?.nome}
        {...getOverrideProps(overrides, "Manaus")}
      ></Text>
    </View>
  );
}
